name: DropRateController
version: '1.0'
main: com.koirdsuzu.dropRateController.DropRateController
api-version: '1.13'
authors: [koirdsuzu]
description: アイテムのドロップ率を変えるプラグイン
website: https://github.com/koirdsuzu/
commands:
  dropchance:
    description: Manage the drop chance for items.
    usage: /dropchance <get|set> [value]
permissions:
  dropratecontroller.use:
    description: Allows access to the dropchance command.
    default: op
  dropratecontroller.bypass:
    description: Admin drops the all items permission.
    default: op
